# Generated by Django 5.0.6 on 2024-07-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
